AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tacostats

  periodically grab comments from the r/neoliberal DT and gather some basic statistics

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  Stats:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:latest
      ImageConfig:
        Command: 
          - tacostats.stats.lambda_handler
      # Environment:
      #   Variables:
      #     TABLE_NAME: my-table
      #     STAGE: prod
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, et equivs: 12,16,21
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 16,20,1 * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  # post a recap of yesterday's stats in the morning
  StatsRecap:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:latest
      ImageConfig:
        Command: 
          - tacostats.stats.lambda_handler
      Environment:
        Variables:
          RECAP: True
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, 9et
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  # post keywords 
  Keywords:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 384
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:latest
      ImageConfig:
        Command: 
          - tacostats.keywords.lambda_handler
      # Environment:
      #   Variables:
      #     RECAP: True
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, et equiv: 16,21
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(17 20,1 * * ? *)
            Enabled: True
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  # post a recap of yesterday's keywords in the morning
  KeywordsRecap:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 256
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:latest
      ImageConfig:
        Command: 
          - tacostats.keywords.lambda_handler
      Environment:
        Variables:
          RECAP: True
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, 10et
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
