version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tacostats"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uecpxvcgek53"
s3_prefix = "tacostats"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["Harvester=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.1.1", "HarvesterRecap=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.1.1", "Stats=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.1.1", "StatsRecap=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.1.1", "Keywords=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.1.1", "KeywordsRecap=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.1.1"]
