version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tacostats"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uecpxvcgek53"
s3_prefix = "tacostats"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["UserStats=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.8", "Harvester=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.8", "HarvesterRecap=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.8", "Stats=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.8", "StatsRecap=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.8", "Keywords=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.8", "KeywordsRecap=676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.8"]
